name: Publish to Marketplace

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build C++ Simulator Core
        run: npm run build-sim

      - name: Compile Extension
        run: npm run compile

      - name: Bump Version
        id: bump # Added an ID to reference the new version if needed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # npm version also creates a git tag by default
          npm version ${{ github.event.inputs.version_bump }} -m "chore: bump version to %s [skip ci]"

      - name: Push Changes
        run: |
          # Push the commit and the tag back to the repo
          git push origin main --follow-tags

      - name: Publish to Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}